abdolence/slack-morphism-rust

src/models/src/common/mod.rs
SlackConversationType::PUBLIC and SlackConversationType::PRIVATE should convert to "public_channel" and "private_channel", instead of just "public" and "private".
See https://api.slack.com/methods/conversations.list .
=> Fix to_string for SlackConversationType

src/models/src/blocks/datetime.rs, src/models/src/common/mod.rs, src/models/src/events/command.rs
- Updated Date formatting and User Mentions according to https://api.slack.com/reference/surfaces/formatting
- Updated Commands response formatting according to https://api.slack.com/interactivity/slash-commands
=> Update Slack's special formatting characters

src/models/src/common/channel.rs
SlackChannelInfo::priority should f64, instead of u64.
See https://api.slack.com/methods/conversations.info .
=> Fix priority type for SlackChannelInfo

src/models/src/blocks/kit.rs
Slack block kit supports headers, this commit adds support for those in the model.
=> Expand kit support for header block type.

src/models/src/common/user.rs
This changes the type of `tz_offset` from `i16` to `i32`.
[`tz_offset` is the number of seconds to offset UTC time by](https://api.slack.com/types/user).
If the offset is greater than 9 hours, it is outside i16 range when represented in seconds.
I found this subtle bug because one of my coworkers appears to be in Honolulu, prompting the deserialization to error.
=> Fix bug in range of supported timezones in `SlackUser`

src/hyper/Cargo.toml, src/hyper/src/connector.rs, src/hyper/src/lib.rs, src/hyper/src/listener/command_events.rs, src/hyper/src/listener/interaction_events.rs, src/hyper/src/listener/mod.rs, src/hyper/src/listener/oauth.rs, src/hyper/src/listener/push_events.rs, src/hyper/src/socket_mode/mod.rs
This adds support for using any hyper connector; `SlackClientHyperConnector` is made generic over types `H` satisfying trait bounds `'static + Send + Sync + Clone + hyper::client::connect::Connect`.
In particular, I have added support for using an http proxy with new alias `SlackHyperProxyClient`.
Usage would look like this:
```
let hyper_connector = SlackClientHyperConnector::with_proxy("http://proxy.domain:3333");
```
The type alias `SlackHyperClient` is unchanged and the constructor name is distinct from `new()`, so the changes are non-breaking wherever these have been used.
=> Add support for using any hyper connector

src/hyper/src/connector.rs
Implement `From<hyper_rustls::HttpsConnector>` for
`SlackClientHyperConnector`. This allows us to use custom SSL
certificate validation for unit tests based on mock servers.
=> feat: implement From trait for SlackClientHyperConnector from an arbitrary HttpsConnector

src/models/src/events/push.rs
Currently used in [this project](https://github.com/noxasaxon/songwhip-bot-rs).
API - https://api.slack.com/events/link_shared
Allows you to receive events when links from up to 5 different domains are shared to _any_ channel/group
Created a `SlackLinkSharedEvent` struct, and updated the `SlackEventCallbackBody` to use serde's rename_all `snake_case` instead of manually writing out the rename attribute for each variant
=> Add model and support for Slack's `link_shared` event push callback subtype

src/models/src/events/push.rs
I received this payload on our prod
```
{"envelope_id":"becda5ef-218c-451c-ac02-d7176d310efb","payload":{"token":"hRcCJba8Je3CQu4LmsDNH5Ww","team_id":"T02AXGU3Z","api_app_id":"A02RNKPNM0S","event":{"type":"message","subtype":"thread_broadcast","text":"I\\u2019ll rollback anyway. What\\u2019s the procedure to rollback now that _redacted_ is fubared?","user":"U01QMNRB16G","ts":"1644918787.343029","thread_ts":"1644918662.376269","root":{"client_msg_id":"9978f034-7622-4548-ae46-c41bd1a5a5db","type":"message","text":"I just deployed _redacted_ :point_up::skin-tone-4:","user":"U01QMNRB16G","ts":"1644918662.376269","team":"T02AXGU3Z","blocks":[{"type":"rich_text","block_id":"yRCm9","elements":[{"type":"rich_text_section","elements":[{"type":"text","text":"I just deployed _redacted_ …
```
=> Add `thread_broadcast` to MessageEvent subtype

src/models/src/messages/mod.rs
We're receiving push event messages with an `attachments` field. The documentation suggests that it is deprecated, so I guess it's coming from a bot that hasn't updated yet - https://api.slack.com/reference/messaging/attachments
Payload:
```json
{
"envelope_id": "3b2f0dd3-fca2-434a-af1c-229802e8c758",
"payload": {
"token": "TCH9ALGhvItarICBAz9D4jkg",
"team_id": "T02AXGU3Z",
"api_app_id": "A0349GSJ1GQ",
"event": {
"bot_id": "B2FTJGLCS",
"type": "message",
"text": "",
"user": "U2FTC7AC9",
"ts": "1645622380.932749",
"team": "T02AXGU3Z",
"bot_profile": {
"id": "B2FTJGLCS",
"deleted": false,
"name": "_redacted_",
"updated": 1599299357,
"app_id": "A1FKYAUUX",
"icons": {
"image_36": "https:\\/\\/avatars.slack-edge.com\\/2021-01-25\\/1680548373876_08bcd7da61f0761d9dcd_36.png",
"image_48": …
```
=> Add slack message attachments

src/client/src/api/chat.rs
👋 hey @abdolence, quick fix for get_permalink. [According to the docs](https://api.slack.com/methods/chat.getPermalink), I think the existing response struct is malformed
=> fix get_permalink response struct

src/models/src/events/push.rs
Due to error:
```
\"unknown variant `channel_leave`, expected one of `bot_message`, `me_message`, `channel_join`, `bot_add`, `bot_remove`, `channel_topic`, `channel_purpose`, `channel_name`, `message_changed`, `message_deleted`, `thread_broadcast`, `tombstone`, `joiner_notification`, `slackbot_response`\"
```
In payload:
```
{
"envelope_id": "7070764d-a47c-4969-9638-64dcd9dbb832",
"payload": {
"token": "hRcCJba8Je3CQu4LmsDNH5Ww",
"team_id": "_redacted_",
"api_app_id": "_redacted_",
"event": {
"type": "message",
"subtype": "channel_leave",
"ts": "1649770793.940659",
"user": "UMVCS7CDU",
"text": "<@UMVCS7CDU> has left the channel",
"channel": "C033G46KA8L",
"event_ts": "1649770793.940659",
"channel_type": "channel"
},
"type": "event_callback",
"event_id": "Ev03ARCB2PD5",
"event_time": …
```
=> Add `channel_leave` message push type

src/models/src/files/mod.rs
Fields in many structs in models crate, excepting `SlackFile` is currently public and can be accessed from other crates. In addition, `SlackMessageContent` struct has a `files` field of type `Option<Vec<SlackFile>>`, which is public. Thus, we cannot read files from this field across crates due to the missing visibility specifier.
This pull request proposes to add `pub`-s to fields in `SlackFile` struct, like other many-many structs.
=> Publish fields in SlackFile struct

src/models/src/common/user.rs
Added a new field so that custom statuses with emoji can be set.
https://api.slack.com/docs/presence-and-status#user-presence-and-status__custom-status__writing-custom-statuses
=> Add `status_emoji` to `SlackUserProfile`

src/client/src/api/chat.rs
After sending a request to chat.postMessage endpoint, `SlackApiChatPostMessageResponse` will be retrieved from the API response. It includes `SlackMessage`, so I expected to get `ChannelId` where the message sent from `SlackMessageOrigin::channel`. However the field is always empty even if the API response contains `channel` field.
Payload of the response looks like:
```json
{
"ts": "123456789.12345",
"channel": "C123456789",
"message": {
...
}
}
```
In this payload, `.message` is mapped to `SlackMessage` and it does not include `.message.channel` in their fields. It was required to use `.channel` instead.
This pull request introduces a new `channel` field on `SlackApiChatPostMessageResponse` to access the field as described above.
=> feat: Add channel field to response of chat.postMessage

src/models/src/blocks/kit.rs, src/models/src/blocks/view.rs, src/models/src/events/interaction.rs
Currently view values in view_submission events are `serde_json::Value`, which is too loose. To fix the type narrower, this pull request proposes to change the type into `HashMap<SlackBlockId, HashMap<SlackActionId, SlackViewStateValue>>`. This structure is documented at https://api.slack.com/reference/interaction-payloads/views#view_submission .
This PR additionally adds `trigger_id` fields into `SlackInteractionViewSubmissionEvent` and `SlackInteractionViewClosedEvent`, which is not documented but actually exists in the payload.
=> feat: Fix type of view values in view_submission event

src/client/Cargo.toml, src/client/src/api/apps.rs, src/client/src/client.rs, src/client/src/errors.rs, src/client/src/token.rs, src/hyper/src/connector.rs, src/models/src/apps/manifest.rs, src/models/src/apps/mod.rs, src/models/src/common/mod.rs, src/models/src/lib.rs
This pull request adds support for these API methods:
- [apps.manifest.create](https://api.slack.com/methods/apps.manifest.create)
- [apps.manifest.delete](https://api.slack.com/methods/apps.manifest.delete)
- [apps.manifest.export](https://api.slack.com/methods/apps.manifest.export)
- [apps.manifest.update](https://api.slack.com/methods/apps.manifest.update)
- [apps.manifest.validate](https://api.slack.com/methods/apps.manifest.validate)
Note that:
- These APIs requires a special token: App Configuration Token, which can be issued in https://api.slack.com/authentication/config-tokens .
- These are in Beta.
Our internal pull request (in Japanese): https://github.com/yumemi-inc/slack-morphism-rust/pull/19
=> feat: Add missing support for apps.manifest.* APIs

src/models/src/common/mod.rs, src/models/src/common/reaction.rs, src/models/src/files/mod.rs, src/models/src/messages/mod.rs
This pull request proposes to add `reactions` field (of type `SlackReactions`), which is documented at https://api.slack.com/methods/reactions.get#examples .
Note that this field is filled only from `reactions.get` endpoint with the message that has any reaction(s), but this approach is better than defining another type for it to share other fields.
=> feat: Add reactions into SlackMessageContent struct

src/models/src/events/push.rs
Hello! 👋🏼 
Thanks for putting this together! I was doing a small hackathon and noticed there wasn't support for the [emoji_changed](https://api.slack.com/events/emoji_changed) event, so I figured why not add it :D 
Let me know if I missed anything, still trying to learn Rust!
=> added support for emoji_changed event

src/api/users.rs
This pull requests a missing paramter `team_id` to `users.list` API. The parameter is defined in the documentation: https://api.slack.com/methods/users.list .
=> feat: Add missing parameter `team_id` to SlackApiUsersListRequest

src/models/messages/mod.rs
API endpoints that returns a posted mesasge, such as `chat.postMessage`, also returns the sender of the message. It is documented in an example below, and enough to use `SlackMessageSender` for them.
https://api.slack.com/methods/chat.postMessage#examples
=> feat: Add sender into SlackMessage struct

src/models/events/mod.rs, src/models/events/view.rs
I added `ViewSubmissionResponse` used for slack app interactivity request.
I confused about location of the file. Is there any better location?
ref. https://github.com/slack-go/slack/blob/master/views.go
=> Support ViewSubmissionResponse for slack app interactivity

src/api/usergroups.rs
Resolve #145
Add `usergroup` argument.
=> fix: Add required argument for usergroups.users.list API

Cargo.toml, docs/src/SUMMARY.md, docs/src/observability-tracing.md, docs/src/web-api.md, examples/client.rs, examples/client_with_tracing.rs, src/api/webhook.rs, src/client.rs, src/hyper_tokio/connector.rs
Another option is to use `session` is to use function `run_in_session`:
```rust,noplaypen
// Sessions are lightweight and basically just a reference to client and token
client
.run_in_session(&token, |session| async move {
let test: SlackApiTestResponse = session
.api_test(&SlackApiTestRequest::new().with_foo("Test".into()))
.await?;
println!("{:#?}", test);
let auth_test = session.auth_test().await?;
println!("{:#?}", auth_test);
Ok(())
})
.await?;
```
Tracing example:
```rust
let token: SlackApiToken =
SlackApiToken::new(token_value).with_team_id(config_env_var("SLACK_TEST_TEAM_ID")?.into()); // While Team ID is optional but still useful for tracing and rate control purposes
// Sessions are lightweight and basically just a reference to client and token
let my_custom_span = …
```
=> Distributed tracing (spans) support, scope propagation and `SlackClient.run_in_session` implementation

src/api/conversations.rs, src/api/reactions.rs, src/models/common/reaction.rs
Related to #153 
This adds:
* reactions.add
* reactions.remove
* Fixes bug in conversations.replies where timestamp was being passed in as channel.
Tested by updating the Cargo.toml of my Slackbot to point to my local crate path and added/removed reactions in my Slack workspace successfully.
=> Add the reactions.add and reactions.remove api. Fix typo in converations_replies.

src/models/blocks/kit.rs
I've been playing around with a Slack Bot in Rust, and have run into some serde problems with using Block Kit. I've added the relevant models that I'm using, and adjusted the existing `placerholder` properties to match the [reference docs](https://api.slack.com/reference/block-kit/block-elements). 
* Added [NumberInput](https://api.slack.com/reference/block-kit/block-elements#number)
* Added [URLInput](https://api.slack.com/reference/block-kit/block-elements#url)
* Made `placeholder` optional across the models, since it doesn't seem to be required anywhere
=> BlockKit Model fixes

src/client.rs
`SlackClient` contains just an `Arc` to the underlying connector, so making it `Clone` seems natural and simplifies code that has to move the client (e.g. spawning an async task).
=> Derive Clone on SlackClient

src/models/blocks/kit.rs
This changes introduces the Time Picker from the Block Kit.
Documentation: https://api.slack.com/reference/block-kit/block-elements#timepicker
=> feat: add support for time picker block

src/models/blocks/view.rs
Currently, when using DateTimePicker[^1] the data from it cannot be seen on the state view while handling Action events. 
This commit adds the extra field that is sent for this element.
The field is an optional UNIX Timestamp, as seen, for example, from the Go Slack API[^2] and Java Slack API [^3].
[^1]: https://api.slack.com/reference/block-kit/block-elements#datetimepicker
[^2]: https://github.com/slack-go/slack/blob/b4b5a6428b1d432dabb23dda46b6898010a8a521/block.go#L53
[^3]: https://github.com/slackapi/java-slack-sdk/blob/33b56c1ae2188307423298599bd53e232d613ce1/slack-api-model/src/main/java/com/slack/api/model/view/ViewState.java#L28
=> feat: add DateTime picker state value

src/models/blocks/kit.rs
model param reference here: https://api.slack.com/reference/block-kit/block-elements#external_multi_select__fields
=> add "min_query_length" param for external selects

src/models/events/push.rs
This pull request adds the following Slack API events into `src/models/events/push.rs` that were missing:
- `file_created` (as `SlackFileCreatedEvent`)
- `file_change` (as `SlackFileChangedEvent`)
- `file_deleted` (as `SlackFileDeletedEvent`)
- `file_shared` (as `SlackFileSharedEvent`)
- `file_unshared` (as `SlackFileUnsharedEvent`)
- `file_public` (as `SlackFilePublicEvent`)
Adding these events help prevent protocol errors in socket mode when files are uploaded/deleted to the channel and a callback function has been set with `SlackSocketModeListenerCallbacks::with_push_events()`.
The fields in the event structs are copied from the Slack API documentation and named accordingly.
=> Add several missing file events

src/models/messages/mod.rs
This field was missing from the `SlackMessageAttachment` object, was required in my use-case for parsing the full message object sent by a webhook.
=> SlackMessageAttachment: add `text` field

Cargo.toml
[Cargo audit](https://crates.io/crates/cargo-audit) is a tool that audits your dependencies for crates with security vulnerabilities reported to the [RustSec Advisory Database](https://github.com/RustSec/advisory-db/).
Running cargo audit before resulted in:
```console
Scanning Cargo.lock for vulnerabilities (289 crate dependencies)
Crate:     tungstenite
Version:   0.20.0
Title:     Tungstenite allows remote attackers to cause a denial of service
Date:      2023-09-25
ID:        RUSTSEC-2023-0065
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0065
Severity:  7.5 (high)
Solution:  Upgrade to >=0.20.1
Dependency tree:
tungstenite 0.20.0
└── tokio-tungstenite 0.20.0
└── slack-morphism 1.14.3
└── slack-bot 0.1.0
```
Updating tokio-tungstenite to 0.20.1 fixes this and it doesn't …
=> Update tokio-tungstenite to 0.20.1 to fix cargo audit high vulnerability

src/models/common/user.rs
Today, Slack API suddenly stopped returning `team_id` on our enterprise workspace.
Instead, now the API returns `teams` with multiple team IDs in the enterprise.
This pull request changes `team_id` to `Option<SlackTeamId>` and adds `teams` field.
This is an example of `users.info` response:
```json
{
"ok": true,
"user": {
"id": "[REDACTED]",
"name": "n_ikeguchi",
"deleted": false,
"color": "8469bc",
"real_name": "Natsuki Ikeguchi",
"tz": "Asia\\/Tokyo",
"tz_label": "Japan Standard Time",
"tz_offset": 32400,
"profile": {
"title": "[REDACTED]",
"phone": "[REDACTED]",
"skype": "",
"real_name": "Natsuki Ikeguchi",
"real_name_normalized": "Natsuki Ikeguchi",
"display_name": "siketyan",
"display_name_normalized": "siketyan",
"fields": null,
"status_text": "[REDACTED]",
"status_emoji": …
```
=> fix!: Allow SlackUser.team_id to be optional, it is not returned on enterprise workspace

src/models/events/fixtures/message_changed.json, src/models/events/push.rs
- Fix struct to correctly parse current event's `ts` and edited message's `ts` property.
- I needed the original message `ts` to reconcile it correctly in my datastore.
- Add parse test.
- Haven't included the `previous_message` field in the updated type defintion because I couldn't find public documentation about it, but it seems to be present in the payload for change events.
Closes #224
=> Fix SlackMessageEventEdited include original message's id

src/models/events/fixtures/message_changed_by_bot.json, src/models/events/push.rs
Closes #229 
This pull request proposes to use `SlackMessageSender` instead of only `SlackUserId` in `SlackMessageEventEdited` struct. This also changes `user` field to optional and supports `bot_id`.
> [!Warning]
> BREAKING CHANGE: SlackMessageEventEdited::user is moved to sender.user and now it is optional.
=> fix!: Include SlackMessageSender in SlackMessageEventEdited

Cargo.toml, examples/axum_events_api_server.rs, examples/client.rs, examples/client_with_tracing.rs, examples/events_api_server.rs, examples/proxy_client.rs, examples/rate_control_client.rs, examples/socket_mode.rs, examples/state_management.rs, examples/webhook_message.rs, src/axum_support/mod.rs, src/axum_support/slack_events_middleware.rs, src/axum_support/slack_oauth_routes.rs, src/client.rs, src/hyper_tokio/connector.rs, src/hyper_tokio/hyper_errors.rs, src/hyper_tokio/hyper_ext.rs, src/hyper_tokio/listener/command_events.rs, src/hyper_tokio/listener/interaction_events.rs, src/hyper_tokio/listener/mod.rs, src/hyper_tokio/listener/oauth.rs, src/hyper_tokio/listener/push_events.rs, src/hyper_tokio/mod.rs, src/hyper_tokio/socket_mode/mod.rs, src/hyper_tokio/socket_mode/tokio_clients_manager.rs, src/listener.rs, src/socket_mode/callbacks.rs, src/socket_mode/clients_manager_listener.rs
Supersedes #219, #220, #222, #233
=> Upgrade http / hyper to 1.0 (axum 0.7)

Cargo.toml, src/lib.rs
`ring` is failing to compile for wasm targets.
As `ring` is only used for the signature verification and is only useful when either `hyper` or `axum` features are enabled, this PR disables the signature verification when none of these features are enabled.
=> feat: Disable signature verification when not needed

src/models/common/mod.rs, src/models/common/star.rs, src/models/events/push.rs
Add support for `star_added` and `star_removed` Slack events. 
It has now been renamed "saved for later" in the Slack UI.
=> feat: Add support for stars events

src/models/common/star.rs
For destructuring such struct, it's required to set attributes visibility to public.
=> fix: Make SlackStarsItem* struct attributes public

src/models/common/bot.rs
According to the [Slack documentation](https://api.slack.com/methods/bots.info), `user_id` is optional:
> If the bot corresponds directly to a bot user account, the bot will also have a `user_id`
=> fix: Make `user_id` attribute on `SlackBotInfo`

Cargo.toml, src/models/events/push.rs
`link_shared` events in the Slack developer sandboxes do not contain the
`source` and `unfurl_id` options anymore, as the associated
[`chat.unfurl`](https://api.slack.com/methods/chat.unfurl) API method
now mandates passing the `(channel, ts)` tuple over the
`(source, unfurl_id)` one
> Both channel and ts must be provided together, or unfurl_id and source
must be provided together.
_And_ `channel`, `ts` are marked as required arguments.
Close: #259
=> fix: allow deserialization of recent link_shared

src/hyper_tokio/hyper_ext.rs, src/token.rs
User session token (`xoxc-...`) requires a special cookie (`d=xoxd-...`) to be set for all requests. This PR adds support of setting a custom cookie to support such cookies.
See https://papermtn.co.uk/retrieving-and-using-slack-cookies-for-authentication/ for information, as `xoxc-..` tokens are mysteriously not documented in [official Slack docs](https://api.slack.com/concepts/token-types).
=> Support passing cookie with token

src/models/messages/mod.rs
Some Slack message blocks may be found as attachments to a message.
Even if attachments are deprecated, as of now, they are still here 🤷
=> Add `blocks` to message attachment

src/models/events/command.rs
Adds `team_domain` and `channel_name` fields to `SlackCommandEvent`. I use this library for my company's project and noticed they're missing.
From slack doc: https://api.slack.com/interactivity/slash-commands#app_command_handling 
> team_id, enterprise_id, channel_id, etc.
> The various accompanying *_name values provide you with the plain text names for these IDs
In the payload example, `team_domain` and `channel_name` are present.
=> Add name fields to SlackCommandEvent

src/hyper_tokio/listener/interaction_events.rs, src/models/events/interaction.rs
Adding block_suggestion interaction event support. 
> A block_suggestion payload is received when a user interacts with a [select menu of external data source](https://api.slack.com/reference/block-kit/block-elements#external_select) element. Users may return a maximum of 100 options or option groups when handling the block_suggestion payload.
* Add `BlockSuggestion` to `SlackInteractionEvent`.  https://api.slack.com/reference/interaction-payloads/block-suggestion
* Add `SlackBlockSuggestionResponse`.  https://api.slack.com/reference/block-kit/block-elements#external_select
* Implement `SlackInteractionEventResponse` for hyper_tokio listener
Closes https://github.com/abdolence/slack-morphism-rust/issues/186
=> Add external select menu support

src/models/common/user.rs
Slack sends an integer in the `user_count` field of a user group, there is no need to try to parse it as a string.
The example in the [Slack documentation](https://api.slack.com/methods/usergroups.list) is wrong as the `user_count` is a string but when using "Tester", the `user_count` is an integer.
=> fix: Update `SlackUserGroup.user_count` JSON type

src/models/messages/mod.rs
Parent message can have the following params:
- `subscribed` when the user has subscribed to a Slack thread
- `last_read` with the `SlackTs` of the latest read message in a Slack thread
=> Add more parent message params

src/lib.rs
I am implementing a custom connector and this module is necessary in order to implement the connector trait (unless I am doing something wrong?).
This function in particular
```rust
fn http_post_uri_multipart_form<'a, 'p, RS, PT, TS>(
&'a self,
full_uri: Url,
file: Option<FileMultipartData<'p>>,
params: &'p PT,
context: SlackClientApiCallContext<'a>,
) -> BoxFuture<'a, ClientResult<RS>>
```
`FileMultipartData` itself is declared public. However, it is inaccessible behind the private module. Another solution is to re-export it as public.
=> refactor: make multipart_form public

src/models/messages/mod.rs
When retrieving a Slack thread using `conversations.replies`, the returned messages may embed a `user_profile` or `bot_profile`.
For example, it happens when the message sender is external to the Slack workspace requested.
=> Add user and bot profiles embedded in a message

src/models/blocks/kit.rs
This PR adds the support for the `video` Slack block documented [here](https://api.slack.com/reference/block-kit/blocks#video).
=> fix: Add `video` Slack block

src/models/common/mod.rs
This PR implements `SlackTextFormat` for `SlackUserGroupId`. It returns the slack subteam format (e.g., `<!subteam^S12345>` that can be used to mention groups in messages. <https://api.slack.com/reference/surfaces/formatting#mentioning-groups>
=> feat: Implement SlackTextFormat for SlackUserGroupId

src/api/emoji.rs, src/api/fixtures/slack_api_emoji_list_response.json, src/models/common/emoji.rs
My initial implementation was actually buggy.
Indeed, Slack response to `emoji.list` contains URLs with escaped `/`.
Here is an example:
```json
{
"ok": true,
"emoji": {
"test": "https:\/\/emoji.slack-edge.com\/test_emoji.png"
},
"cache_ts": "1742309006.064153"
}
```
The deserializer was thus unable to parse the URL and failed.
=> fix: Fix `emoji_list` response deserialization

src/models/events/push.rs
This PR adds `previous_message` field, which is required by my application.
I'm not sure this PR should be merged since `previous_message` is not defined in any official documents.
ref. https://github.com/abdolence/slack-morphism-rust/pull/226#issue-2031822736
=> Support previous_message in SlackMessageEvent

src/api/chat.rs
The new API allows use to use channel/ts as identifiers while also using slack blocks. Fixes #318.
=> Unfurl API for channel/ts + slack blocks.
